// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = "https://hfmpmrlwduhtegkjaclu.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmbXBtcmx3ZHVodGVna2phY2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNjcwMjEsImV4cCI6MjA3ODg0MzAyMX0._q8HTYOY5hcWWVptD1X5aXL2WEYKPcn5MbFGfSZQows";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);